name: Déploiement API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Copier la clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ma-cle-ssh.pem
          chmod 600 ~/.ssh/ma-cle-ssh.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}

      - name: Ajouter la clé SSH
        run: |
          echo "$SSH_KEY" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Ajouter le host à known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 34.79.156.176 >> ~/.ssh/known_hosts

      - name: Vérification de la clé
        run: |
          file /tmp/id_rsa
          head -n 5 /tmp/id_rsa

      - name: Lancer le playbook Ansible
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml \
            --private-key=/tmp/id_rsa \
