name: Déploiement API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Copier la clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > /Users/fratia.theo/Desktop/TP_CICD.ssh 
          chmod 600 /Users/fratia.theo/Desktop/TP_CICD.ssh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ajouter la clé SSH
        run: |
          echo "$SSH_KEY" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Lancer le playbook Ansible
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml \
            --private-key=/tmp/id_rsa \
            --ssh-extra-args="-o StrictHostKeyChecking=no"
